name: Humble CI

on:
  push:
    branches:
      - master
  schedule:
    # Run every Friday at 6:30 am to detect breaking APIs
    - cron: '30 6 * * 5'
    
jobs:
  humble_source:
    runs-on: ubuntu-22.04
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: 3d_rec
          target-ros2-distro: humble
